services:
  ojp-nova:
    build:
      context: .
      platforms:
        - linux/amd64
        - linux/arm64
    image: skiplus-ojp-nova
    environment:
      - LOGS_DIR=/var/logs
      - GENERATED_DIR=/var/generated
    volumes:
      - /var/skiplus:/var
    ports:
      - "81:80"

